// export const UPDATE_DATING_FORM_DATA = "UPDATE_DATING_FORM_DATA"
// export const 

export const UPDATE_DATING_HOBBIES_VALUES = "UPDATE_DATING_HOBBIES_VALUES"

export const GET_DATING_USERS_REQUEST = "GET_DATING_USERS_REQUEST"
export const GET_DATING_USERS_SUCCESS = "GET_DATING_USERS_SUCCESS"
export const GET_DATING_USERS_FAILURE = "GET_DATING_USERS_FAILURE"