// export const UPDATE_DATING_FORM_DATA = "UPDATE_DATING_FORM_DATA"
// export const 

export const UPDATE_DATING_HOBBIES_VALUES = "UPDATE_DATING_HOBBIES_VALUES"

export const GET_DATING_USERS_REQUEST = "GET_DATING_USERS_REQUEST"
export const GET_DATING_USERS_SUCCESS = "GET_DATING_USERS_SUCCESS"
export const GET_DATING_USERS_FAILURE = "GET_DATING_USERS_FAILURE"

export const UPDATE_GENERAL_SECTION_REQUEST = "UPDATE_GENERAL_SECTION_REQUEST"
export const UPDATE_GENERAL_SECTION_SUCCESS = "UPDATE_GENERAL_SECTION_SUCCESS"
export const UPDATE_GENERAL_SECTION_FALIURE = "UPDATE_GENERAL_SECTION_FALIURE"

export const GET_DATING_USER_BY_ID_REQUEST = "GET_DATING_USER_BY_ID_REQUEST"
export const GET_DATING_USER_BY_ID_SUCCESS = "GET_DATING_USER_BY_ID_SUCCESS"
export const GET_DATING_USER_BY_ID_FALIURE = "GET_DATING_USER_BY_ID_FALIURE"

export const GET_DATING_CATEGORY_REQUEST = "GET_DATING_CATEGORY_REQUEST"
export const GET_DATING_CATEGORY_SUCCESS = "GET_DATING_CATEGORY_SUCCESS"
export const GET_DATING_CATEGORY_FALIURE = "GET_DATING_CATEGORY_FALIURE"

export const GET_ACCEPTED_DATING_REQUEST_DATA_REQUEST = "GET_ACCEPTED_DATING_REQUEST_DATA_REQUEST"
export const GET_ACCEPTED_DATING_REQUEST_DATA_SUCCESS = "GET_ACCEPTED_DATING_REQUEST_DATA_SUCCESS"
export const GET_ACCEPTED_DATING_REQUEST_DATA_FAILURE = "GET_ACCEPTED_DATING_REQUEST_DATA_FAILURE"
